In [1]:
import numpy as np
import pandas as pd
import math
from sklearn.metrics import classification_report, confusion_matrix
import acquire as acq
import prepare as prep
from sklearn.linear_model import LogisticRegression

In [2]:
titanic = acq.get_titanic_data()
#keep age, fare, pclass
#drop passenger_id, sex, sibsp, parch, embarked, class, deck, embark_town, alone
titanic = titanic.drop(['passenger_id', 'sex', 'embarked', 'class', 'deck', 'embark_town', 'alone'], axis = 1)
titanic = titanic.drop([ 'sibsp', 'parch'], axis = 1)
titanic.head()

csv file found and loaded


survived  pclass   age     fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [3]:
X = titanic.drop(columns= 'survived')
Y = titanic.survived

X = pd.DataFrame(X)
Y = pd.DataFrame(Y)

X_train, X_validate, X_test, y_train, y_validate, y_test = acq.train_validate_test_split(X, Y)

In [4]:
#X_train["age"].fillna(["age"].mean(),inplace= True)
#nba["College"].fillna("No College", inplace = True)
X_train["age"] = X_train["age"].fillna(X_train["age"].mean())
X_validate["age"] = X_validate["age"].fillna(X_validate["age"].mean())
X_test["age"] = X_test["age"].fillna(X_test["age"].mean())

In [5]:
X_train = pd.DataFrame(X_train)
X_validate = pd.DataFrame(X_validate)
X_test = pd.DataFrame(X_test)
y_train = pd.DataFrame(y_train)
y_validate = pd.DataFrame(y_validate)
y_test = pd.DataFrame(y_test)

In [6]:
y_train = y_train.survived

In [7]:
y_train.head()

455    1
380    1
492    0
55     1
243    0
Name: survived, dtype: int64

In [8]:
X_train

pclass        age      fare
455       3  29.000000    7.8958
380       1  42.000000  227.5250
492       1  55.000000   30.5000
55        1  29.393566   35.5000
243       3  22.000000    7.1250
..      ...        ...       ...
695       2  52.000000   13.5000
128       3  29.393566   22.3583
636       3  32.000000    7.9250
222       3  51.000000    8.0500
496       1  54.000000   78.2667

[534 rows x 3 columns]

Create a model that includes only age, fare, and pclass. Does this model perform better than your baseline? 

No, it does not.

In [9]:
#create object
log1 = LogisticRegression()
log1

LogisticRegression()

In [10]:
X_train.head()

pclass        age      fare
455       3  29.000000    7.8958
380       1  42.000000  227.5250
492       1  55.000000   30.5000
55        1  29.393566   35.5000
243       3  22.000000    7.1250

In [11]:
#fit it, this makes it ready to make predictions
log1.fit(X_train, y_train)

LogisticRegression()

In [12]:
#use it, gives accuracy of model
log1.score(X_train, y_train)

0.7059925093632958

In [13]:
#take a look at predictions
log1.predict(X_train)[:5]

array([0, 1, 0, 1, 0])

In [14]:
#view raw probabilities(output from the model)
log1.predict_proba(X_train).round(2)[:5]

array([[0.77, 0.23],
       [0.31, 0.69],
       [0.51, 0.49],
       [0.33, 0.67],
       [0.73, 0.27]])

In [15]:
#classification report
print(classification_report(y_train, log1.predict(X_train)))

              precision    recall  f1-score   support

           0       0.71      0.87      0.79       329
           1       0.68      0.44      0.53       205

    accuracy                           0.71       534
   macro avg       0.70      0.66      0.66       534
weighted avg       0.70      0.71      0.69       534



In [16]:
#coef

log1.coef_

array([[-0.92542941, -0.02948528,  0.0022624 ]])

In [17]:
#fit 2nd the model

In [18]:
#make prediction

In [19]:
titanic.head()

survived  pclass   age     fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

Include sex in your model as well. Note that you'll need to encode or create a dummy variable of this feature before including it in a model.

In [20]:
titanic = acq.get_titanic_data()
titanic = acq.prep_data(titanic)
titanic.head()

csv file found and loaded
Columns with null values: Index(['age', 'embarked', 'deck', 'embark_town'], dtype='object')


passenger_id  survived  pclass     sex  sibsp  parch     fare  class  alone
0             0         0       3    male      1      0   7.2500  Third      0
1             1         1       1  female      1      0  71.2833  First      0
2             2         1       3  female      0      0   7.9250  Third      1
3             3         1       1  female      1      0  53.1000  First      0
4             4         0       3    male      0      0   8.0500  Third      1

In [21]:
X = titanic.drop(columns= 'survived')
Y = titanic.survived

X = pd.DataFrame(X)
Y = pd.DataFrame(Y)

X_train, X_validate, X_test, y_train, y_validate, y_test = acq.train_validate_test_split(X, Y)

In [22]:
X_train["age"] = X_train["age"].fillna(X_train["age"].mean())
X_validate["age"] = X_validate["age"].fillna(X_validate["age"].mean())
X_test["age"] = X_test["age"].fillna(X_test["age"].mean())

KeyError: 'age'

In [ ]:
X_train = pd.DataFrame(X_train)
X_validate = pd.DataFrame(X_validate)
X_test = pd.DataFrame(X_test)
y_train = pd.DataFrame(y_train)
y_validate = pd.DataFrame(y_validate)
y_test = pd.DataFrame(y_test)

In [ ]:
X_train.head()

In [ ]:
log2 = LogisticRegression()
log2

In [ ]:
log2.fit(X_train, y_train)

In [ ]:
log2.score(X_train, y_train)

In [ ]:
print(classification_report(y_train, log2.predict(X_train)))

Try out other combinations of features and models.

Use you best 3 models to predict and evaluate on your validate sample.

Choose you best model from the validation performation, and evaluate it on the test dataset. How do the performance metrics compare to validate? to train?



In [ ]:
titanic = acq.prep